version: '2'

services:
    activemq:
        image: webcenter/activemq:latest
        ports: 
            - "1099:1099"
            - "8161:8161"
            - "61616:61616"
            - "61613:61613"
        volumes:
            - ~/volumes/activemq/data/activemq:/data/activemq
            - ~/volumes/activemq/var/log/activemq:/var/log/activemq
        environment: 
            ACTIVEMQ_ADMIN_LOGIN: admin
            ACTIVEMQ_ADMIN_PASSWORD: admin
