version: '2'

services:
    nexus3:
        image: sonatype/nexus3:3.2.0
        container_name: nexus3
        ports:
            - "8082:8081"
        volumes:
            - ~/volumes/nexus-data:/nexus-data
        networks:
            - nexus3net

networks:
    nexus3net:
        driver: bridge