version: '3'

services:
    nexus3:
        image: sonatype/nexus3:3.15.2
        container_name: nexus3
        ports:
            - "9081:8081"
        volumes:
            - nexus-data:/nexus-data
        networks:
            - nexus3net

networks:
    nexus3net:
        driver: bridge

volumes:
    nexus-data: