version: '2'

services:
    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss
        container_name: artifactory
        ports:
            - 9091:8081
        volumes:
            - ~/volumes/artifactory/data:/var/opt/jfrog/artifactory/data
            - ~/volumes/artifactory/logs:/var/opt/jfrog/artifactory/logs
            - ~/volumes/artifactory/backup:/var/opt/jfrog/artifactory/backup
            - ~/volumes/artifactory/etc:/var/opt/jfrog/artifactory/etc
