version: '2'

services:
    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss
        container_name: artifactory
        ports:
            - 8081:8081
        volumes:
            - artifactory_data:/var/opt/jfrog/artifactory/data
            - artifactory_logs:/var/opt/jfrog/artifactory/logs
            - artifactory_backup:/var/opt/jfrog/artifactory/backup
            - artifactory_etc:/var/opt/jfrog/artifactory/etc

volumes:
    artifactory_data:
    artifactory_logs:
    artifactory_backup:
    artifactory_etc:
