version: '2'

services:
    artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss
        container_name: artifactory
        ports:
            - 8081:8081
        volumes:
            - $ARTIFACTORY_HOME/data:/var/opt/jfrog/artifactory/data
            - $ARTIFACTORY_HOME/logs:/var/opt/jfrog/artifactory/logs
            - $ARTIFACTORY_HOME/backup:/var/opt/jfrog/artifactory/backup
            - $ARTIFACTORY_HOME/etc:/var/opt/jfrog/artifactory/etc