version: '2'

services:
    postgres:
        image: postgres:9.6.3-alpine
        ports: 
            - "5432:5432"
        volumes:
            - ~/volumes/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: somepassword
