version: '3'

services:
  redis:
    image: redis:3.2.3-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
        - redis_data:/data

volumes:
  redis_data: